percent: 50
setTime: 23450

includeMiners: false
groundLevel: 64

alerts:
  MORNING:
    ACTIONBAR:
      enabled: true
      text: 'Ночь пропущена! (%sleeping/%needed)'

    CHAT:
      enabled: false
      text: 'Ночь пропущена! (%sleeping/%needed)'

  SLEEP:
    ACTIONBAR:
      enabled: true
      text: '&e%player &fлег в кровать! (%sleeping/%needed)'

    CHAT:
      enabled: false
      text: '&e%player &fлег в кровать! (%sleeping/%needed)'

  WAKE:
    ACTIONBAR:
      enabled: true
      text: '&e%player &fВстал с кровати! (%sleeping/%needed)'

    CHAT:
      enabled: false
      text: '&e%player &fВстал с кровати! (%sleeping/%needed)'

messages:
  no-rights: 'У вас нет прав чтобы сделать это!'
  reload-command: '&eПерезапуск плагина: &f/fs reload'
  successfully-reload: 'Успешно перезагружен!'